# Generated by Django 3.1.10 on 2021-05-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mainimage',
        ),
    ]
